### ISSUE TITLE
starboard

### ISSUE THREAD

**Issue by pikaninja** [Phxntxm/Tanya#6]
i require starboard plis or i kill

**Comment by XuaTheGrate** [comment]
🔪

**Comment by IAmTomahawkx** [comment]
can reproduce on canary

**Comment by Phxntxm** [comment]
No repro

**Comment by pikaninja** [comment]
can repro ⭐⭐⭐⭐

**Comment by Phxntxm** [comment]
Won't fix 
![image](https://user-images.githubusercontent.com/3664828/119288004-375a2100-bbf4-11eb-9a15-166ed837fcf0.png)
